var res = {

    MainScene_json : "res/BaseGame.json",
    PickScene_json : "res/PickBonus.json",
    JesterWheelScene_json : "res/JesterWheel.json",
    glowburst_png  : "res/source/Bonus/PickYourPoison/glowburst.png",
    glowburst_plist : "res/source/Bonus/PickYourPoison/glowburst.plist",
    Pickoneflip_png  : "res/source/Bonus/PickYourPoison/Pickoneflip.png",
    Pickoneflip_plist : "res/source/Bonus/PickYourPoison/Pickoneflip.plist",
    Pickoneflip_png1  : "res/source/Reels/Ace/Animated/Ace.png",
    Pickoneflip_plist1 : "res/source/Reels/Ace/Animated/Ace.plist",
    Pickoneflip_png2  : "res/source/Reels/Jack/Animated/Jack.png",
    Pickoneflip_plist2 : "res/source/Reels/Jack/Animated/Jack.plist",
    Pickoneflip_png11  : "res/source/Reels/Queen/Animated/Queen.png",
    Pickoneflip_plist11 : "res/source/Reels/Queen/Animated/Queen.plist",
    Pickoneflip_png12  : "res/source/Reels/Ten/Animated/Ten.png",
    Pickoneflip_plist12 : "res/source/Reels/Ten/Animated/Ten.plist",
    Pickoneflip_png5  : "res/source/Reels/King/Animated/King.png",
    Pickoneflip_plist5 : "res/source/Reels/King/Animated/King.plist",
    Pickoneflip_png8  : "res/source/Reels/Nine/Animated/Nine.png",
    Pickoneflip_plist8 : "res/source/Reels/Nine/Animated/Nine.plist",
    Pickoneflip_png3  : "res/source/Reels/FreeSpin/Animated/FreeSpin.png",
    Pickoneflip_plist3 : "res/source/Reels/FreeSpin/Animated/FreeSpin.plist",
    Pickoneflip_png4  : "res/source/Reels/Hurricane/Animated/Hurricane.png",
    Pickoneflip_plist4 : "res/source/Reels/Hurricane/Animated/Hurricane.plist",
    Pickoneflip_png6  : "res/source/Reels/KingCake/Animated/KingCake.png",
    Pickoneflip_plist6 : "res/source/Reels/KingCake/Animated/KingCake.plist",
    Pickoneflip_png7  : "res/source/Reels/Mask/Animated/Mask.png",
    Pickoneflip_plist7 : "res/source/Reels/Mask/Animated/Mask.plist",
    Pickoneflip_png9  : "res/source/Reels/PartyGirl/Animated/PartyGirl.png",
    Pickoneflip_plist9 : "res/source/Reels/PartyGirl/Animated/PartyGirl.plist",
    Pickoneflip_png10  : "res/source/Reels/Pick/Animated/Pick.png",
    Pickoneflip_plist10 : "res/source/Reels/Pick/Animated/Pick.plist",
    Pickoneflip_png13  : "res/source/Reels/Wheel/Animated/Wheel.png",
    Pickoneflip_plist13 : "res/source/Reels/Wheel/Animated/Wheel.plist",
    Pickoneflip_png14  : "res/source/Reels/Wild_2x/Animated/Wild_2x.png",
    Pickoneflip_plist14 : "res/source/Reels/Wild_2x/Animated/Wild_2x.plist",
    Pickoneflip_png15  : "res/source/Reels/Wild_3x/Animated/Wild_3x.png",
    Pickoneflip_plist15 : "res/source/Reels/Wild_3x/Animated/Wild_3x.plist",
    Pickoneflip_png16  : "res/source/Reels/Wild_4x/Animated/Wild_4x.png",
    Pickoneflip_plist16 : "res/source/Reels/Wild_4x/Animated/Wild_4x.plist",
    Pickoneflip_png17  : "res/source/Reels/Wild0/Animated/Wild0.png",
    Pickoneflip_plist17 : "res/source/Reels/Wild0/Animated/Wild0.plist",
    Pickoneflip_png18  : "res/source/Reels/Wild1/Animated/Wild1.png",
    Pickoneflip_plist18 : "res/source/Reels/Wild1/Animated/Wild1.plist",
    Pickoneflip_png19  : "res/source/Reels/Wild2/Animated/Wild2.png",
    Pickoneflip_plist19 : "res/source/Reels/Wild2/Animated/Wild2.plist"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
